### ISSUE TITLE
Logos für Asymptote etc.

### ISSUE THREAD

**Issue by yellow-panther** [malu/asymptote#1]
Hallo malu,
![asymptote 1](https://user-images.githubusercontent.com/17721887/43573042-2180c4f0-9641-11e8-8932-c2a38e3ce399.jpg)
![asymptote 2](https://user-images.githubusercontent.com/17721887/43573050-28c86178-9641-11e8-9126-e138c18aa734.jpg)
![asymptote 3](https://user-images.githubusercontent.com/17721887/43573074-3496203a-9641-11e8-87f3-342d24e9856e.jpg)
![asymptote 4](https://user-images.githubusercontent.com/17721887/43573096-3e937074-9641-11e8-8a98-150c61f9015d.jpg)
man kann diese -umgewandelt im Bitmap Format z.B. mit http://www.photofiltre.com/  - für graphische Benutzeroberflächen wie Arena, ChessGUI oder WinBoard Interface verwenden vgl. http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list 

Laufen denn die Darwin Applikationen auch unter Mac OS? Ich nutze nur Windows 7/10.

**Comment by malu** [comment]
Hey,
entschuldige, dass meine Antwort so lang auf sich warten lässt.

Mir gefällt das zweite, darf ich das benutzen? :)

Ob das ganze auch auf MacOS läuft, weiß ich tatsächlich nicht mit Sicherheit, weil ich es nicht persönlich getestet habe. Aber ich gehe davon aus (bis jemand das Gegenteil behauptet ;)).

**Comment by yellow-panther** [comment]
von mir aus besteht gegen die Verwendung von Logo 2 keine Bedenken, vgl. http://asymptote.sourceforge.net/ (open source)

**Comment by malu** [comment]
Dann benutze ich das Logo wohl lieber nicht.
Trotzdem danke. ;)

**Comment by yellow-panther** [comment]
Dariusz aus  Polen hat mir bestätigt, daß Asymptote Darwin unter Mac OS High Sierra normal läuft, https://inkscape.org/de/ zur Ansicht der  PNG-Dateien
[Mac OS X Screenshots.zip](https://github.com/malu/asymptote/files/2351753/Mac.OS.X.Screenshots.zip)
wegen der Logos gibt es hier auch noch genügend andere Beispiele https://www.google.de/search?q=asymptote&source=lnms&tbm=isch&sa=X&ved=0ahUKEwio5fbLr6PdAhXBblAKHbC7C4YQ_AUIDCgD&biw=1280&bih=910
